# -*- coding: utf-8 -*-
"""instructions (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jHJzA_bJp-4MTuWp2BYeOKvAO9QQ3sO6

# **Client behavior classification in Banking**
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
# %matplotlib inline
plt.rcParams["figure.figsize"] = (8, 6)
# Data transformation
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.preprocessing import MinMaxScaler
# Features Selection
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2, mutual_info_classif
# Classificators
from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
# warnings deactivate
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('/content/sample_data/bank-additional-full.csv', sep = ';')
df.head(5)

df.shape

df.info()

col_cat = list(df.select_dtypes(include=['object']).columns)
col_cat

df['job'].unique()

X = df.iloc[:,:-1]  #input columns
y = df.iloc[:,-1]    #target column

from sklearn.preprocessing import OrdinalEncoder

col_cat = list(X.select_dtypes(include=['category']).columns)

oe = OrdinalEncoder()
oe.fit(X[col_cat])

X_cat_enc = oe.transform(X[col_cat])

X_cat_enc

X_cat_enc = pd.DataFrame(X_cat_enc)
X_cat_enc.columns = col_cat
X_cat_enc

from sklearn.preprocessing import MinMaxScaler

# Select numerical columns
col_num = list(X.select_dtypes(include=['int64', 'float64']).columns)

# Apply scaling
scaler = MinMaxScaler(feature_range=(0, 1))
X_num_enc = scaler.fit_transform(X[col_num])

X_num_enc

X_num_enc = pd.DataFrame(X_num_enc)
X_num_enc.columns = col_num
X_num_enc

import numpy as np

x_enc = np.hstack((X_num_enc, X_cat_enc))
x_enc

le = LabelEncoder()
le.fit(y)
y_enc = le.transform(y)
y_enc = pd.Series(y_enc)
y_enc.columns = y.name

y

y_enc

bestfeatures = SelectKBest(score_func=chi2, k=10)
fit = bestfeatures.fit(x_enc,y_enc)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)

featureScores = pd.concat([dfcolumns, dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns
print(featureScores.nlargest(10,'Score'))  #print 10 best features

model = ExtraTreesClassifier()
model.fit(x_enc,y_enc)

print(model.feature_importances_)

print(model.feature_importances_)

import pandas as pd

# Create column names
num_cols = col_num
cat_cols = col_cat

all_cols = list(num_cols) + list(cat_cols)

# Convert to DataFrame
x_enc = pd.DataFrame(x_enc, columns=all_cols)

corrmat = x_enc.corr()
top_corr_features = corrmat.index
plt.figure(figsize=(20,20))
g=sns.heatmap(x_enc[top_corr_features].corr(),annot=True,cmap="RdYlGn")

col = x_enc.columns
col

x_enc = x_enc[col]

X_train, X_test, y_train, y_test = train_test_split(x_enc, y_enc, test_size=0.33, random_state=1)
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

model = ExtraTreesClassifier()
model.fit(X_train, y_train)

yhat = model.predict(X_test)
print(yhat)

accuracy = accuracy_score(y_test, yhat)
print('Accuracy: %.2f' % (accuracy*100))

model = DecisionTreeClassifier()
 ##YOUR CODE GOES HERE##

from sklearn.tree import DecisionTreeClassifier

# Step 1: Create model
model = DecisionTreeClassifier()

# Step 2: Train model
model.fit(x_enc, y)

# Step 3: Now you can use feature importance
print("Feature importance:", model.feature_importances_)

feat_importances = pd.Series(model.feature_importances_, index=x_enc.columns)
feat_importances.nlargest(10).plot(kind='barh')
plt.show()

feat_importances.nlargest(10)

col = feat_importances.nlargest(10).index
col

X_train_dt = X_train[col]
X_test_dt = X_test[col]
model.fit(X_train_dt, y_train)
yhat = model.predict(X_test_dt)
accuracy = accuracy_score(y_test, yhat)
print('Accuracy: %.2f' % (accuracy*100))

text_representation = tree.export_text(model)
print(text_representation)

with open("decistion_tree.log", "w") as fout:
    fout.write(text_representation)

fig = plt.figure(figsize=(25,20))
_ = tree.plot_tree(model,
               feature_names = col,
               class_names = y.unique(),
               filled = True)

fig.savefig('decision_tree.png')

import graphviz
dot_data = tree.export_graphviz(model,
               feature_names = col,
               class_names = y.unique(),
                                filled=True)

"""After creation you can draw graph

"""

graph = graphviz.Source(dot_data, format="png")
graph

"""And render it into file:

"""

graph.render("decision_tree_graphivz")

"""## Conclusions

In this lab we learned to do preliminary data processing. In particular, change data types, normalize and process categorical data. It was shown how to make feature selection by different methods. Learned how to build training and test DataSets. Shows how to work with different classifiers. It was also shown how to visualize a decision tree.
As a result of lab it was shown how on the basis of a statistical database predict  if the client will subscribe a term deposit or no.

The accuracy of decision was abot 90%.

## Tasks
"""

model = ExtraTreesClassifier

from sklearn.metrics import accuracy_score

def model_ac(x_train, y_train, x_test, y_test, clf):

    # Train the model
    clf.fit(x_train, y_train)

    # Predictions
    y_pred = clf.predict(x_test)

    # Accuracy
    acc = accuracy_score(y_test, y_pred)

    return acc

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

import pandas as pd

def model_imp(x_train, y_train, clf):

    # Train the model
    clf.fit(x_train, y_train)

    # Get feature importance
    imp = clf.feature_importances_

    # Convert to Series (if DataFrame)
    if hasattr(x_train, "columns"):
        imp_series = pd.Series(imp, index=x_train.columns)
    else:
        imp_series = pd.Series(imp)

    return imp_series

"""<details><summary>Click <b>here</b> for the solution</summary>
<code>    
    model = clf()
    model.fit(x_train, y_train)
    feat_importances = pd.Series(model.feature_importances_, index=x_enc.columns)
    return feat_importances.sort_values(ascending=False)
    </code>
</details>

"""

imp = model_imp(X_train, y_train, model)
print(imp)